### ISSUE TITLE
Oft überschriebene Pixel auf niedrigere Prioritäten setzen

### ISSUE THREAD

**Issue by DerJuulsn** [placeDE/pixel#23]
Wie im Titel beschrieben, wäre es vmtl. sinnvoll z.B. Augen auf eine niedrigere Priorität zu setzen da diese dauernd überschrieben werden und somit wertvolle Ressourcen für andere Dinge verloren gehen.

**Comment by nama17** [comment]
Könnte man auch fürs genaue Gegenteil argumentieren, da häufig überschriebene mehr bekämpft werden müssen. Ich seh in beidem allerdings nicht wirklich Vorteile

**Comment by Zod-** [comment]
Es gibt jetzt priority masken
