### ISSUE TITLE
Geschwindigkeitsbegrenzungslos

### ISSUE THREAD

**Issue by ChrisPhoenix02** [placeDE/pixel#79]

**Comment by Xyaren** [comment]
https://cdn.discordapp.com/attachments/959922396272402502/959960583954890792/schild_neu_neu.png
https://discord.com/channels/297765871122907136/959922396272402502/959960584462409849

x 1094 y 828

**Comment by Xyaren** [comment]
ich versuche mich mal dran. 
Inklusive Autbahn "Frame" also ohne autos und asphalt
