### ISSUE TITLE
Requirements zum hinzufügen neuer Bilder sollten dokumentiert werden

### ISSUE THREAD

**Issue by Xyaren** [placeDE/pixel#82]
Siehe Titel.

Der Einstieg für neue Contributor könnte damit erleichtert werden

**Comment by ChrisPhoenix02** [comment]
**1. Branch** erstellen**- [ ]

**2. Bild in Images-Ordner hinzufügen mit Dateiname:** - [ ]
_beispiel.png_ mit Transparentem Hintergrund und keinem Rand


**3. in config.toml neuen Block hinzufügen:** - [ ]
`[[structure]]
name = "beispiel"
file = "images/beispiel.png"
startx = x-Koordinate
starty = y-Koordinate
priority = 2`
Dabei bezeichnet die Koordinate das oberste linke Pixel der verlinkten png in r/place
und Priority bitte **NICHT** ändern, außer es ist mit dem Rest der Devs abgesprochen.

**4. Terminal in Hauptordner des Repos offenen zwei pyhton-skripte ausführen:** - [ ]
 `python .\scripts\generate_json.py` 
und danach
`python .\scripts\render_json.py`
Es werden drei Dateien erzeugt: output.png, overlay.png und pixel.json

**5. Änderungen Committen und pushen** - [ ]
Betroffene Dateien sind:
config.toml, output.png, overlay.png und pixel.json und images\beispiel.png

**6. Pull Request zum main stellen und von anderem Dev prüfen lassen** - [ ]
